jobs:
  resolve-conflicts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - Show current directory and its contents
        run: |
          pwd
          ls -la

      - name: Check for conflicted Package.appxmanifest
        id: check_conflicted
        run: |
          $isConflicted = git diff --check | Select-String -Pattern "^[+-]{7}\s" -Quiet
          echo "Is Conflicted: $isConflicted"
          echo "IS_CONFLICTED=$isConflicted" >> $GITHUB_ENV

      - name: Resolve conflicts if any
        if: env.IS_CONFLICTED == 'True'
        run: |
          git checkout --theirs -- 'StoryCAD/Package.appxmanifest'
          git add 'StoryCAD/Package.appxmanifest'
          git commit -m "Resolved conflicts in Package.appxmanifest"

      - name: Notify conflict resolution status
        run: |
          if($isConflicted) {
            echo "Conflicts found and resolved."
          } else {
            echo "No conflicts found in Package.appxmanifest."
          }
