name: Resolve Package.appxmanifest Conflicts

on:
  pull_request_target:
    paths:
      - 'StoryCAD/Package.appxmanifest'
    types: [opened, synchronize, reopened]

jobs:
  resolve-conflicts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Check for conflicted Package.appxmanifest
        id: check_conflicted
        run: |
          $isConflicted = (git diff --name-only --diff-filter=U | Select-String -Pattern "StoryCAD/Package.appxmanifest" -Quiet)
          echo "Is Conflicted: $isConflicted"
          echo "::set-output name=is_conflicted::$isConflicted"

      - name: Resolve conflicts if any
        if: steps.check_conflicted.outputs.is_conflicted == 'True'
        run: |
          git config --global user.name 'Automated Conflict Resolver'
          git config --global user.email 'actions@github.com'
          git checkout --theirs -- 'StoryCAD/Package.appxmanifest'
          git add 'StoryCAD/Package.appxmanifest'
          git commit -m "Resolved conflicts in Package.appxmanifest"

      - name: Notify conflict resolution status
        run: |
          $isConflicted = ${{ steps.check_conflicted.outputs.is_conflicted }}
          if($isConflicted -eq 'True') {
            echo "Conflicts found and resolved."
          } else {
            echo "No conflicts found in Package.appxmanifest."
          }
