name: StoryBuilder Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow builds StoryBuilder
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #Installs .NET6
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      #Sets up MSBUILD
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore the nuget projecrts
        run: msbuild storybuilder.sln /t:Restore /p:Configuration=Release

      # build NRTF
      - name: Build NRTF
        run: msbuild NRtfTree\NRtfTree.csproj -t:build -verbosity:normal -property:Configuration=Release

      # builds StoryBuilder lib
      - name: Build StoryBuilderLib
        run: msbuild StoryBuilderLib\StoryBuilderLib.csproj -t:build -verbosity:normal -property:Configuration=Release
        
      # builds StoryBuilder
      - name: Build StoryBuilder
        run: msbuild StoryBuilder\StoryBuilder.csproj -t:build -verbosity:normal -property:Configuration=Release
